import Head from 'next/head'
import { Header } from '../components/Header'
import { Navbar } from '../components/Navbar'
import { Services } from '../components/Services/Services'
import { Works } from '../components/Works'
import { HowItWorks } from '../components/HowItWorks'
import { Pricing } from '../components/Pricing'
import { Features } from '../components/Features'
import { Feedback } from '../components/Feedback'
import { Footer } from '../components/Footer'
import { Index } from '../components/FAQ'

export default function Home() {
  return (
    <div>
      <Head>
        <title>UNIK Creatives - Design Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet" />
      </Head>

      <Navbar />
      <Header />
      <Services />
      <Works />
      <HowItWorks />
      <Pricing />
      <Features />
      <Feedback />
      <Index />
      <Footer />

    </div>
  )
}
