import Head from 'next/head'
import { Header } from '../components/Header'
import { Navbar } from '../components/Navbar'
import { Services } from '../components/Services'
import { Projects } from '../components/Projects'
import { HowItWorks } from '../components/HowItWorks'
import { Pricing } from '../components/Pricing'

export default function Home() {
  return (
    <div>
      <Head>
        <title>UNIK Creatives - Design Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Header />
      <Services />
      <Projects />
      <HowItWorks />
      <Pricing />

    </div>
  )
}
